name: Trusty CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install kogito-runtimes trusty patch
      run: cd end2endPoC && ./setup.sh && cd ..
    - name: Build services and run docker compose
      run: cd end2endPoC && ./run-compose.sh -d && cd ..
    - name: wait until mongodb is responsive
      run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:27017)" != "200" ]]; do sleep 5; done' || false
    - name: add test user to mongodb
      run: mongo admin -u root -p password --host localhost:27017 < ./end2endPoC/pipelines/add-mongo-user.js
    - name: Run integration tests
      run: mvn -f end2endPoC-integrationTests/pom.xml test
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./binder/requirements.txt
        pip install -r ./binder/requirements-dev.txt
        pip install -r ./python-trustyai/requirements.txt
        pip install -r ./python-trustyai/requirements-dev.txt
    - name: Setup python-trustyai dependencies
      run: |
        chmod +x ./python-trustyai/deps.sh
        ./python-trustyai/deps.sh
    - name: Python lint
      run: |
        pylint $(find . -type f -name "*.py")
    - name: Python test
      run: |
        pytest
    - name: Python check format
      run: |
        black --check $(find . -type f -name "*.py")
